// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iU551e6bJvJbCsNM0_wJYB1RCUT3hJM',
    appId: '1:1015781219688:web:7956f85036ee265c790add',
    messagingSenderId: '1015781219688',
    projectId: 'flutterchat-da700',
    authDomain: 'flutterchat-da700.firebaseapp.com',
    storageBucket: 'flutterchat-da700.firebasestorage.app',
    measurementId: 'G-GGCEGLZ0P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRUBAWlESjx42hzbptLveQ8bAYb-stQR8',
    appId: '1:1015781219688:android:cc40e0c6f70bb21a790add',
    messagingSenderId: '1015781219688',
    projectId: 'flutterchat-da700',
    storageBucket: 'flutterchat-da700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWlFB75OcopDnWQGWRNMjmSUdyLlPfFY',
    appId: '1:1015781219688:ios:95b2905a7a826ff6790add',
    messagingSenderId: '1015781219688',
    projectId: 'flutterchat-da700',
    storageBucket: 'flutterchat-da700.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWlFB75OcopDnWQGWRNMjmSUdyLlPfFY',
    appId: '1:1015781219688:ios:95b2905a7a826ff6790add',
    messagingSenderId: '1015781219688',
    projectId: 'flutterchat-da700',
    storageBucket: 'flutterchat-da700.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_iU551e6bJvJbCsNM0_wJYB1RCUT3hJM',
    appId: '1:1015781219688:web:ddf2cd94d0088fa9790add',
    messagingSenderId: '1015781219688',
    projectId: 'flutterchat-da700',
    authDomain: 'flutterchat-da700.firebaseapp.com',
    storageBucket: 'flutterchat-da700.firebasestorage.app',
    measurementId: 'G-2V75MZVCKT',
  );
}
